"""Reporter module - generates human-readable evaluation reports."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from truthbench import __version__
from truthbench.schemas import (
    AggregateEvaluationResult,
    CaseEvaluationResult,
    EvaluationReport,
)


def generate_markdown_report(
    dataset_name: str,
    dataset_version: str,
    aggregate: AggregateEvaluationResult,
    output_path: str | None = None
) -> str:
    """
    Generate a human-readable markdown evaluation report.

    Args:
        dataset_name: Name of the evaluated dataset
        dataset_version: Version of the dataset
        aggregate: Aggregated evaluation results
        output_path: Optional path to save the report

    Returns:
        Markdown report as string
    """
    lines = []

    # Header
    lines.append(f"# TruthBench Evaluation Report")
    lines.append(f"")
    lines.append(f"**Dataset:** {dataset_name} v{dataset_version}")
    lines.append(f"**Generated:** {datetime.utcnow().isoformat()}Z")
    lines.append(f"**Runner Version:** {__version__}")
    lines.append(f"")

    # Summary
    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Test Cases | {aggregate.total_cases} |")
    lines.append(f"| Total Claims Evaluated | {aggregate.total_claims_evaluated} |")
    lines.append(f"| Passed Cases | {aggregate.passed_cases} |")
    lines.append(f"| Failed Cases | {aggregate.failed_cases} |")
    lines.append(f"")
    lines.append(f"### Aggregate Metrics")
    lines.append(f"")
    lines.append(f"| Metric | Score |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Claim Extraction Accuracy | {aggregate.mean_claim_accuracy:.2%} |")
    lines.append(f"| Verdict Accuracy | {aggregate.mean_verdict_accuracy:.2%} |")
    lines.append(f"| Verdict Precision (macro) | {aggregate.mean_verdict_precision:.2%} |")
    lines.append(f"| Verdict Recall (macro) | {aggregate.mean_verdict_recall:.2%} |")
    lines.append(f"| Verdict F1 (macro) | {aggregate.mean_verdict_f1:.2%} |")
    lines.append(f"| Hallucination Rate | {aggregate.mean_hallucination_rate:.2%} |")
    lines.append(f"| Citation Coverage | {aggregate.mean_citation_coverage:.2%} |")
    lines.append(f"| Risk Level Match Rate | {aggregate.risk_level_match_rate:.2%} |")
    lines.append(f"")

    # Per-case results
    lines.append(f"## Per-Case Results")
    lines.append(f"")
    lines.append(f"| Case ID | Claim Acc | Verdict Acc | Verdict F1 | Hallucination Rate | Citation Cov | Risk Match | Issues |")
    lines.append(f"|---------|-----------|-------------|------------|-------------------|--------------|------------|--------|")

    for case in aggregate.case_results:
        issues_str = "; ".join(case.failed_checks) if case.failed_checks else "✓"
        if len(issues_str) > 60:
            issues_str = issues_str[:57] + "..."
        lines.append(
            f"| {case.case_id} | {case.claim_accuracy:.2%} | "
            f"{case.verdict_accuracy:.2%} | {case.verdict_f1:.2%} | "
            f"{case.hallucination_rate:.2%} | {case.citation_coverage:.2%} | "
            f"{'✓' if case.risk_level_match else '✗'} | {issues_str} |"
        )

    lines.append(f"")

    # Failed cases detail
    failed_cases = [c for c in aggregate.case_results if c.failed_checks]
    if failed_cases:
        lines.append(f"## Failed Cases Detail")
        lines.append(f"")
        for case in failed_cases:
            lines.append(f"### {case.case_id}")
            lines.append(f"")
            for issue in case.failed_checks:
                lines.append(f"- {issue}")
            lines.append(f"")

    # Recommendations
    if aggregate.recommendations:
        lines.append(f"## Recommendations")
        lines.append(f"")
        for i, rec in enumerate(aggregate.recommendations, 1):
            lines.append(f"{i}. {rec}")
        lines.append(f"")

    # Footer
    lines.append(f"---")
    lines.append(f"*Report generated by TruthBench v{__version__}*")

    report = "\n".join(lines)

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)

    return report


def generate_json_report(
    dataset_name: str,
    dataset_version: str,
    aggregate: AggregateEvaluationResult,
    output_path: str | None = None
) -> str:
    """Generate a JSON evaluation report."""
    report = EvaluationReport(
        dataset_name=dataset_name,
        dataset_version=dataset_version,
        aggregate_results=aggregate,
        generated_at=datetime.utcnow().isoformat() + "Z",
    )

    json_str = report.model_dump_json(indent=2)

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(json_str)

    return json_str